Copy from template if the entry is empty
raxod502/diary-manager pull request #8
Opened 2022-09-08 04:38 UTC by AlMaVizca

This PR is related to the feature requested on the issue #7 
if `diary-manager-template` is defined, use that specified file as a reference for a new diary entry.

Requirements:
The filename defined on `diary-manager-template` will have to use the same extention defined at `diary-manager-entry-extension`

2022-09-11 00:12 UTC, raxod502 requested changes
Can we instead insert the template text into the buffer after finding the file, rather than copying it before opening? I don't think the implementation in this PR will work if encryption is enabled.

2022-09-15 02:11 UTC, AlMaVizca commented
I'm using it with encryption. The way I have defined it, the template is with the same format (extension); I mean encrypted, too, in my case.
Inserting the content instead of copying the file will make the template format independent from the diary entry.

2022-09-29 20:42 UTC, raxod502 commented
Ah, fair enough. I do like making it format-independent, though, so thanks for the update. I made some further changes in https://github.com/radian-software/diary-manager/pull/8/commits/602ae15f4960207775a733c44141c71aa41f161a for style.

2022-09-29 20:42 UTC, raxod502 approved these changes
:sparkles:

2022-09-29 20:42 UTC, merged